# Generated by Django 5.2.1 on 2025-07-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursepayment_courseenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepayment',
            name='payment_id',
            field=models.CharField(max_length=100),
        ),
    ]
